config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'consoles#index'

  resources :consoles do
    resources :games, shallow: true
  end

  get :export, to: 'exports#export'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/console.rb
class Console < ApplicationRecord
  has_many :games, dependent: :destroy
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :console
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/consoles_controller.rb
class ConsolesController < ApplicationController
  before_action :set_console, only: %i[ show edit update destroy ]

  # GET /consoles or /consoles.json
  def index
    @consoles = Console.all
  end

  # GET /consoles/1 or /consoles/1.json
  def show
  end

  # GET /consoles/new
  def new
    @console = Console.new
  end

  # GET /consoles/1/edit
  def edit
  end

  # POST /consoles or /consoles.json
  def create
    @console = Console.new(console_params)

    respond_to do |format|
      if @console.save
        format.html { redirect_to console_url(@console), notice: "Console was successfully created." }
        format.json { render :show, status: :created, location: @console }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @console.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /consoles/1 or /consoles/1.json
  def update
    respond_to do |format|
      if @console.update(console_params)
        format.html { redirect_to console_url(@console), notice: "Console was successfully updated." }
        format.json { render :show, status: :ok, location: @console }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @console.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consoles/1 or /consoles/1.json
  def destroy
    @console.destroy

    respond_to do |format|
      format.html { redirect_to consoles_url, notice: "Console was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_console
      @console = Console.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def console_params
      params.require(:console).permit(:name)
    end
end

app/controllers/exports_controller.rb
class ExportsController < ApplicationController
  def export
    @export_data = build_export_data

    respond_to do |format|
      format.html { render :export }
      format.json { render json: @export_data }
    end
  end

  private

  def build_export_data
    Console.all.includes(:games).order(:name, 'games.title').map do |console|
      games_data = console.games.map { |game| game.slice(:title) }
      console.slice(:name).merge(games: games_data)
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_console, only: %i[ index new create ]
  before_action :set_game, only: %i[ show edit update destroy ]

  # GET /games or /games.json
  def index
    @games = @console.games.all
  end

  # GET /games/1 or /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = @console.games.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games or /games.json
  def create
    @game = @console.games.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to game_url(@game), notice: "Game was successfully created." }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1 or /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to game_url(@game), notice: "Game was successfully updated." }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1 or /games/1.json
  def destroy
    @game.destroy

    respond_to do |format|
      format.html { redirect_to console_games_url(@game.console), notice: "Game was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def set_console
      @console = Console.find(params[:console_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def game_params
      params.require(:game).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/consoles_helper.rb
module ConsolesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/consoles/_console.html.erb
<div id="<%= dom_id console %>">
  <p>
    <strong>Name:</strong>
    <%= console.name %>
  </p>

  <%= link_to "Show games", console_games_path(console) %>
</div>

app/views/consoles/_form.html.erb
<%= form_with(model: console) do |form| %>
  <% if console.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(console.errors.count, "error") %> prohibited this console from being saved:</h2>

      <ul>
        <% console.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/consoles/edit.html.erb
<h1>Editing console</h1>

<%= render "form", console: @console %>

<br>

<div>
  <%= link_to "Show this console", @console %> |
  <%= link_to "Back to consoles", consoles_path %>
</div>

app/views/consoles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Consoles</h1>

<div id="consoles">
  <% @consoles.each do |console| %>
    <%= render console %>
    <p>
      <%= link_to "Show this console", console %>
    </p>
  <% end %>
</div>

<%= link_to "New console", new_console_path %>

<hr />

<%= link_to "Export", export_path %>

app/views/consoles/new.html.erb
<h1>New console</h1>

<%= render "form", console: @console %>

<br>

<div>
  <%= link_to "Back to consoles", consoles_path %>
</div>

app/views/consoles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @console %>

<div>
  <%= link_to "Edit this console", edit_console_path(@console) %> |
  <%= link_to "Back to consoles", consoles_path %>

  <%= button_to "Destroy this console", @console, method: :delete %>
</div>

app/views/exports/export.html.erb
<h1>Export</h1>

<%= link_to "Back to consoles", consoles_path %>

<pre><%= JSON.pretty_generate(@export_data) %></pre>

app/views/games/_form.html.erb
<%= form_with(model: models) do |form| %>
  <% if game.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :console_id, style: "display: block" %>
    <%= form.text_field :console_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/games/_game.html.erb
<div id="<%= dom_id game %>">
  <p>
    <strong>Title:</strong>
    <%= game.title %>
  </p>

  <p>
    <strong>Console:</strong>
    <%= game.console_id %>
  </p>

</div>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render "form", models: [@game], game: @game %>

<br>

<div>
  <%= link_to "Show this game", @game %> |
  <%= link_to "Back to games", console_games_path(@game.console) %>
</div>

app/views/games/index.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= @console.name %> games</h1>

<div id="games">
  <% @games.each do |game| %>
    <%= render game %>
    <p>
      <%= link_to "Show this game", game %>
    </p>
  <% end %>
</div>

<%= link_to "New game", new_console_game_path(@console) %>
<%= link_to "Back to console", console_path(@console) %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render "form", models: [@console, @game], game: @game %>

<br>

<div>
  <%= link_to "Back to games", console_games_path(@game.console) %>
</div>

app/views/games/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @game %>

<div>
  <%= link_to "Edit this game", edit_game_path(@game) %> |
  <%= link_to "Back to games", console_games_path(@game.console) %>

  <%= button_to "Destroy this game", @game, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsIncludesOrder</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>